<?php

/**
 * @file
 * Primary module hooks for DH Dashboard module.
 */

/**
 * Implements hook_theme().
 */
function dh_dashboard_theme($existing, $type, $theme, $path) {
  return [
    'block__dh_dashboard_news' => [
      'variables' => ['news' => NULL],
      'template' => 'block--dh-dashboard-news',
    ],
    'dh_dashboard_progress' => [
      'variables' => [
        'progress' => [],
      ],
      'template' => 'block--dh-dashboard-progress',
    ],
    'block__dh_dashboard_certificate_info' => [
      'variables' => ['info' => NULL],
      'template' => 'block--dh-dashboard-certificate-info',
    ],
  ];
}

/**
 * Implements hook_preprocess_node().
 */
function dh_dashboard_preprocess_node(&$variables) {
  if ($variables['node']->getType() == 'student_dashboard') {
    $variables['#attached']['library'][] = 'dh_dashboard/dashboard';
  }
}

/**
 * Implements hook_preprocess_block().
 */
function dh_dashboard_preprocess_block(&$variables) {
  \Drupal::messenger()->addStatus('Block type: ' . ($variables['plugin_id'] ?? 'none'));
}
