requirement_set.entity_type:
  type: config_entity
  label: 'Requirement Set'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    list_builder:
      type: string
      label: 'List builder'
      default: 'Drupal\dh_certificate\ListBuilder\RequirementSetListBuilder'