dh_certificate.settings:
  type: config_object
  label: 'DH Certificate settings'
  mapping:
    requirements:
      type: sequence
      label: 'Certificate Requirements'
      sequence:
        type: mapping
        mapping:
          id:
            type: string
            label: 'Requirement ID'
          name:
            type: string
            label: 'Requirement Name'
          type:
            type: string
            label: 'Requirement Type'
          required:
            type: boolean
            label: 'Is Required'
