dh_certificate.requirement_type.*:
  type: config_entity
  label: 'Requirement Type'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    description:
      type: text
      label: 'Description'
    weight:
      type: integer
      label: 'Weight'
    status:
      type: boolean
      label: 'Status'
